added admin.py to `app/sample/` Django app
dadwalakshay/the-django-boilerplate pull request #12
Opened 2022-10-06 17:15 UTC by rishav-singh-0

Referring to #5 issue

2022-10-07 08:30 UTC, dadwalakshay-ai requested changes

2022-10-07 08:30 UTC, dadwalakshay-ai commented on app/sample/admin.py
> +from .models import SampleModel
use absolute imports

2022-10-07 08:35 UTC, dadwalakshay requested changes

2022-10-07 08:35 UTC, dadwalakshay commented on app/sample/admin.py
> +from .models import SampleModel
Use absolute imports and follow pep-8 convention for it.

Refer to this documentation link -> https://peps.python.org/pep-0008/#imports

2022-10-08 13:09 UTC, rishav-singh-0 reviewed
Done

2022-10-09 11:57 UTC, dadwalakshay approved these changes

2022-10-09 11:58 UTC, merged